version: '3.1'

networks: 
  backend:
#  daroachnetwork:
#    external: true

services:
  mongo:
    image: mongo:latest
    restart: always
    ports: 
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    networks:
      - backend
    volumes:
      - ${MONGO_DB_STORAGE}:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - ${ME_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${DB_USER}:${DB_PASS}@mongo:27017"
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASS}
    networks:
      - backend
    depends_on:
      - mongo
