FROM node:18-alpine

RUN mkdir -p /dnet
WORKDIR /dnet

COPY www/package.json ./

RUN npm install

COPY www /dnet

RUN npm run build

CMD [ "node", "/dnet/.output/server/index.mjs" ]

# # RUN chmod 777 /dnet

# CMD ["npm", "run", "dev"]
# # CMD ["nuxt", "dev"]
