import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="container m-auto">
      <Head>
        <title>www.daroach.net - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Daroach.net!</a>
        </h1>
        <div className="p-10">
          <Image src="/donuts.gif" alt="" width={600} height={800}/>
        </div>
      </main>

      <footer className={styles.footer}>
        <span>www.daroach.net - running on a high performance webserver in my apartment</span>
      </footer>
    </div>
  )
}
